### ISSUE TITLE
Incorrect Link Rendering on UnoCSS Plugin Page

### ISSUE THREAD

**Issue by quadratz** [lumeland/lume.land#114]
On the page https://lume.land/plugins/unocss/, the intended hyperlink https://unocss.dev/guide/config-file is incorrectly displayed as [{@link https://unocss.dev/guide/config-file}](https://lume.land/plugins/unocss/%7B@link%20https://unocss.dev/guide/config-file%7D).

![image](https://github.com/lumeland/lume.land/assets/74030149/da9fe2da-5f87-4864-a450-0c9a625bf278)

**Comment by oscarotero** [comment]
Thanks! It's a bug in the Lume jsdoc. It will be fixed when the next Lume version is released
