### ISSUE TITLE
Fix dead link for vento

### ISSUE THREAD

**Issue by UppaJung** [lumeland/lume.land#119]
@oscarotero

It appears you forgot to replaced a (now dead) link to https://oscarotero.github.io/vento/ with https://vento.js.org/, leaving folks who learn about Vento on the Lume site unable to find out more about Vento

https://github.com/lumeland/lume.land/blob/c38ea1b11500a4f430f1082aa67c1b3bce5c1ea6/plugins/vento.md?plain=1#L12C1-L12C45

**Comment by oscarotero** [comment]
I just fixed it.
Thanks for letting me know!
