### ISSUE TITLE
Pagefind doesn't work without `--allow-run` but the error message is not helpful

### ISSUE THREAD

**Issue by dogfuntom** [lumeland/lume.land#133]
How to reproduce:

1. Install `Simple Blog` theme using the `deno run -A https://lume.land/init.ts`.
2. In `lume` task change permissions to `--allow-net --allow-read --allow-write=./_site --allow-sys=homedir --allow-env --allow-run=git`.
3. Attempt to run. The error like below will be there.
4. Remove the `=git` part. No error will be there.

The error is:
```
TypeError: Cannot read properties of null (reading 'on')
    {{# I omitted a few lines here. #}}
    at https://deno.land/x/lume@v2.2.4/plugins/pagefind.ts:139:40
    at Processors.run (https://deno.land/x/lume@v2.2.4/core/processors.ts:32:13)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async Site.#buildPages (https://deno.land/x/lume@v2.2.4/core/site.ts:689:5)
    at async Site.build (https://deno.land/x/lume@v2.2.4/core/site.ts:532:9)
```

**Comment by oscarotero** [comment]
This is because pagefind resolves the binary [dynamically with this function](https://github.com/CloudCannon/pagefind/blob/main/wrappers/node/lib/resolveBinary.js).

And the path of this binary depends on the platform and version. This one works fine to me:

```
--allow-run=git,/Users/oscarotero/Library/Caches/deno/npm/registry.npmjs.org/@pagefind/darwin-x64/1.1.0/bin/pagefind_extended
```

But maybe in your case is a different path. I don't know if there's a good way to improve this.

**Comment by dogfuntom** [comment]
Personally I’d like a note on [plugin’s page].

Possibly in similar style to how MDN handles tricky pitfalls – arbitrary examples:

- <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules#troubleshooting>
- <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr#notes>
- <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#usage_notes>

(Consulting the [plugin’s page] is the first thing I tried because, as I hoped, it could be a known problem related to order of operations or something similar.)

[plugin’s page]: https://lume.land/plugins/pagefind/

**Comment by oscarotero** [comment]
Good idea. Maybe each plugin should have a **Permissions** section to indicate which permissions are required to run it.

**Comment by oscarotero** [comment]
I've added a Permissions section https://lume.land/plugins/pagefind/#permissions
