### ISSUE TITLE
A sample of adding a filter into Vento

### ISSUE THREAD

**Issue by dogfuntom** [lumeland/lume.land#138]
``` typescript
site.hooks.vento((vento: Environment) => {
  Object.assign(vento.filters, { withoutAll })
})
```

It seems to work in my case. But I'm not certain about:

- how can it be added into docs using the right terminology
- whether is it free of pitfalls
- whether is it as idiomatic as possible

**Comment by oscarotero** [comment]
There's the `site.filter()` function to add filters to all template engines installed.

```js
site.filter("withoutAll", withoutAll);
```

More info: https://lume.land/docs/configuration/filters/#filters

**Comment by dogfuntom** [comment]
Oh, ok, not sure how I missed that…
Sorry for redundant issue then.
