### ISSUE TITLE
Propose I18n system

### ISSUE THREAD

**Issue by AugustinMauroy** [lumeland/lume.land#43]
Adding a translation system allows more people to discover Lume

**Comment by jrson83** [comment]
My native language is not english, but I personally think it is not a good idea to translate the documentation into other languages. The effort to maintain the additional languages would be much too high.

**Comment by AugustinMauroy** [comment]
The multilingual plugin is already implemented in lume and there is even an open issue to modify it to be more efficient

**Comment by jrson83** [comment]
> The multilingual plugin is already implemented in lume and there is even an open issue to modify it to be more efficient

I know. So what is this issue about?
