### ISSUE TITLE
Improve documentation for index files

### ISSUE THREAD

**Issue by scarf005** [lumeland/lume.land#59]
i'm not sure if i should move this issue to https://github.com/lumeland/lume, but i guess it belong here since it's related to documentations.

# Summary
improve documentation for index files by  adding section to describe 

1. how lume finds and uses index files
2. which file extension will be accepted as valid index file (index.templ.ts, index.tsx, etc)
3. how could user load custom index file to `lume()` (like `lume.data()`)

## Motivation

sometimes how lume works feels automagical, and documentation often does not fully address lume's internals. 

![image](https://user-images.githubusercontent.com/54838975/222436251-98835981-a19e-40d9-bd9b-6f72cf566780.png)

today i was trying to use `index.tsx` file, and somehow it failed to load. i searched through the docs yet the only example was using with ['index.md'](https://lume.land/docs/getting-started/your-first-page/#the-page-file). only after reading [deno blog post](https://deno.com/blog/build-a-static-site-with-lume#list-all-posts) i could be certain that other index files were supported.

**Comment by oscarotero** [comment]
I'm not sure to understand.
What do you mean with "index files"? Files that indexes content (like pagination) or files named `index`? 
Index page files are like any other page file. I mean you can create a page using Markdown, Nunjucks, JSX, TypeScript, etc. The only difference is it's named `index`, so it's saved as `index.html`.

**Comment by scarf005** [comment]
i mean the files that gets converted to index.html, such as index.md or index.tsx or index.tmpl.ts. currently lumeland lack docs for these.

**Comment by oscarotero** [comment]
Okay. It's not explicitly mentioned but you can see an example of index.md compared with other file names here: https://lume.land/docs/creating-pages/page-files/

Basically, in prettyUrls mode, all pages are converted to `index.hml` (`about.njk` => `about/index.html`).
And if prettyUrls is disabled, the pages keep the original name adding the `.html` extension (`about.njk` => `about.html`).

Is this the information you're missing?

**Comment by scarf005** [comment]
yes, now i get it. thanks for clarifying.
