### ISSUE TITLE
Same LICENSE as Lume?

### ISSUE THREAD

**Issue by cameronelliott** [lumeland/lume.land#6]
Hey, Lume & Lume.land look great! Could I use this repo as a starter for my documentation?

That would be cool, but I really need to see a license to feel good about it.

I see Lume is MIT?
Any chance you want to release this as MIT also?
If yes, could you please add a file?
Thanks for sharing this cool work.
Cameron

**Comment by oscarotero** [comment]
Yeah, no problem. I just added the license file.
