### ISSUE TITLE
Use tsx over jsx in documentation

### ISSUE THREAD

**Issue by scarf005** [lumeland/lume.land#60]
# Summary

```tsx
import type { Data, PageHelpers } from 'lume/core.ts';

export default (
    { title, children }: Data,
    filters: PageHelpers
) => (
  <html>
    <head>
      <title>{title}</title>
    </head>
    <body>
      {children}
    </body>
  </html>
);
```

replace examples in [jsx](https://lume.land/plugins/jsx/), [jsx preact](https://lume.land/plugins/jsx_preact/) with tsx.

## Motivation

majority of template engines lume supports does not have type system (nunjucks, liquid, etc...). however, users of tsx and tsx preact could benefit by using typescript definitions. for example, it would be helpful to show that layouts uses `Data` type.

**Comment by oscarotero** [comment]
The use of JSX for the examples is for simplicity. TSX is a bit verbose and JSX is more clear. But yeah, probably some examples could have both formats.

**Comment by LeoDog896** [comment]
Possibly do something similar to [SvelteKit] and allow switching between the two? (e.g. tabs or a toggle - but a toggle might be a bit too much :sweat_smile:)
